order/urls.py
from django.urls import path
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from .views import (add_order,ViewBuyerApp, view_struc_drawings,dealer_view, vendor_quotations,
                    view_quotations, exterior_view, interior_view,
                    view_container_orders,view_container_order_items, view_report_sap, view_arc_drawings, view_3d_model, OrderForm)
from django.contrib.auth.decorators import user_passes_test

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='order/login.html',redirect_authenticated_user=True),
         name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    
    path('view/structural-drawings',view_struc_drawings, name="struc-drawings"),
    path('view/architectural-drawings',view_arc_drawings, name="arc-drawings"),
    path('view/reportsap', view_report_sap, name="report-sap"),
    path('3d/model', view_3d_model, name='model-3d'),

    path('buyer/applications',ViewBuyerApp.as_view(), name="buyer-app"),

    path('dealer/',dealer_view, name="dealer-view"),
    path('quotation/',vendor_quotations, name="vendor-quotation"),
    path('view/quotation/',view_quotations, name="view-quotation"),
    
    path('interior-view/', interior_view, name='interior-view'),
    path('exterior-view/', exterior_view, name='exterior-view'),

    path('add-order/', add_order, name='add-order'),

    path('order-form/',OrderForm.as_view(condition_dict={'5': OrderForm.check_user_authentication}), name='order-form'),

    path('container/orders', view_container_orders, name='view-container-orders'), #for admin
    path('container/order/items/<int:pk>/', view_container_order_items, name='view-container-order-items'),
    path('my/orders', view_container_order_items, name='my-orders'),# for users history
]

shipping/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('order.urls')),
    path('', include('users.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/models.py
from django.db import models
from multiselectfield import MultiSelectField
from localflavor.us.models import USZipCodeField
from phonenumber_field.modelfields import PhoneNumberField
from django.core.validators import MinValueValidator
from users.models import User

# Create your models here.

class Order(models.Model):
    Type_Of_Climate_Area = (
        ('select all','Select All'),
        ('Heavy Snow Load','Heavy Snow Load'),
        ('High Wind','High Wind'),
        ('Tornado','Tornado'),
        ('Earthquake','Earthquake'),
        ('Desert','Desert'),
        ('Other','Other '),
    )
    YES_NO_CHOICES = (
        ('yes', 'Yes'),
        ('no', 'No')
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=None, blank=True, null=True)
    f_name = models.CharField('First Name',max_length=100)
    l_name = models.CharField('Last Name',max_length=100)
    email = models.EmailField('Email',max_length=100, help_text="Optional", blank=True, null=True)
    company_name = models.CharField('Name of Company',max_length=100, help_text="Optional", blank=True, null=True)
    # phone_number = PhoneNumberField(("Phone Number"), max_length = 18, help_text="Optional", blank=True, null=True)
    phone_number = models.CharField(("Phone Number"), max_length = 18, help_text="Optional", blank=True, null=True)
  
    zipcode = USZipCodeField("Zip Code",blank=True, null=True)
    
    letter_of_credit = models.CharField("Do you have a Letter of Credit?", max_length=5, choices= YES_NO_CHOICES, blank=True, null=True)
    how_much_letter_of_credit= models.CharField("What is the value of your Letter of Credit (in USD)?",max_length=50, help_text="in USD$", blank=True, null=True)

    line_of_credit = models.CharField("Do you have a Line of Credit?", max_length=5, choices= YES_NO_CHOICES, blank=True, null=True)
    how_much_line_of_credit= models.CharField("What is the currently unused amount in your Line of Credit?",max_length=50, help_text="in USD$",blank=True, null=True)

    STATUS_CHOICES = (("3-6 Months","3-6 Months"),
        ("6-9 Months", "6-9 Months"),
        ("1 Year or More", "1 Year or More"),
        )

    When_To_Order =(
        ('urgent','Urgent(within 30 days)'),
        ('other','Other'),
        )
    when_to_order = models.CharField("When are you looking to order?",choices=When_To_Order ,max_length=50, default=None, null=True, blank=True)
    other_when_to_order = models.CharField("When To Order",choices=STATUS_CHOICES ,max_length=50, default=None, null=True, blank=True)
    
    type_of_climate_area = MultiSelectField("On which type of climate area(s) will the development(s) be sited? ",choices=Type_Of_Climate_Area, max_length=300, blank=True, null=True)
    other_type_of_climate_area =models.CharField(max_length=200, verbose_name="Other", null=True, blank=True)

    septic_infrastructure  = models.CharField("Does the development site already have septic infrastructure or service?",choices=YES_NO_CHOICES, max_length=100, blank=True, null=True)

    installation_septic_infrastructure  = models.CharField("Does it require the installation of septic infrastructure? (There will be a charge for initial infrastructure installation and periodic maintenance service charges.) ",choices=YES_NO_CHOICES, max_length=100, blank=True, null=True, default=None)

    class Meta:
        verbose_name = "Buyer Application"
        verbose_name_plural = "Buyer Applications"


class Material(models.Model):
    """Material Required showing this data to vendors for quotations"""
    name = models.CharField("Material Name", max_length=100)


class MaterialQuotations(models.Model):
    material_name = models.CharField("Material Name", max_length=100,default=None)
    user_name = models.CharField("Name:", max_length=100)
    company_name = models.CharField("Company Name:", max_length=100)
    price = models.CharField("Price", max_length=100)
    time_date = models.DateTimeField("Quotation Date", auto_now_add=True)

    class Meta:
        verbose_name = "MaterialQuotation"
        verbose_name_plural = "MaterialQuotations"


class ContainerPricing(models.Model):
    no_of_floors = models.CharField("No. of Floors", max_length=100)
    variant = models.CharField("Variant", max_length=100)
    square_feet = models.CharField("Approximate Square Feet", max_length=100)
    price = models.DecimalField("Price", max_digits=20, decimal_places=2)
    price21 = models.DecimalField("Delivered Price Delivered to site for 21 or more units", max_digits=20, decimal_places=2, blank=True, null=True)
    model_image = models.CharField("Model Image", max_length=1000, blank=True, null=True)
    model_name = models.CharField("Model Name", max_length=100, blank=True, null=True, default='')
    model_link = models.CharField("model_link", max_length=10, blank=True, null=True, default='')
    class Meta:
        verbose_name = "Containers Pricing"
        verbose_name_plural = "Containers Pricing"

    def __str__(self):
        return f"{self.no_of_floors} {self.variant}"


class CustomContainerPricing(models.Model):
    sqfeet_per_room = models.CharField("Approximate Square Feet per room", max_length=100)
    custom_price = models.DecimalField("Price per 290s.f. room(for 20units or less)", max_digits=20, decimal_places=2)
    custom_price21 = models.DecimalField("Price per 290s.f. room(for 21units or more)", max_digits=20, decimal_places=2, blank=True, null=True) 
    class Meta:
        verbose_name = "Custom Containers Pricing"
        verbose_name_plural = "Custom  Containers Pricing"

    def __str__(self):
        return f"Custom Container Pricing"


class DeliveryInfo(models.Model):
    address = models.CharField('Address', max_length=1000, default='')
    city = models.CharField('City',max_length=60, default='')
    state = models.CharField('State',max_length=60, default='')
    postal = USZipCodeField('Postal',max_length=60, default='')
    country = models.CharField('Country',max_length=60, default='')
    delivery_date = models.DateField(default=None)

    class Meta:
        verbose_name = "Delivery Info"
        verbose_name_plural = "Delivery Info"


class CartOrder(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    delivery_info_obj = models.ForeignKey(DeliveryInfo, on_delete=models.CASCADE, default=None, blank=True, null=True)
    buyer_app_obj = models.ForeignKey(Order, on_delete=models.CASCADE, default=None, blank=True, null=True)
    order_items = models.ForeignKey(ContainerPricing, on_delete=models.CASCADE, blank=True, null=True)
    custom_order = models.ForeignKey(CustomContainerPricing, on_delete=models.CASCADE, blank=True, null=True)
    custom_floors = models.CharField("No. of Floors", max_length=100, blank=True, null=True)
    custom_width = models.CharField("Width", max_length=100, blank=True, null=True)
    custom_depth = models.CharField("Depth", max_length=100, blank=True, null=True)
    quantity = models.PositiveIntegerField("Quantity")
    ordered_on = models.DateField(auto_now_add=True)
    furnishing_option = models.CharField('furnishing_option', max_length=100, blank=True, null=True)
    user_image = models.ImageField(upload_to="pdf-images", blank=True, null=True, default="default.jpeg")

    class Meta:
        verbose_name = "Shipping Home Order"
        verbose_name_plural = "Shipping Home Orders"

users/models.py
from PIL import Image
from django.db import models
from datetime import datetime
from django.utils import timezone
from multiselectfield import MultiSelectField
from django.core.validators import RegexValidator
from django.contrib.auth.models import AbstractUser
from phonenumber_field.modelfields import PhoneNumberField
# Create Models

class User(AbstractUser):
    email = models.EmailField(verbose_name='email address',max_length=255,unique=True)
    username = models.CharField(verbose_name='Username',max_length=255,default=None, blank=True, null= True)
    
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    @property
    def is_dealer(self):
        try:
            self.dealer
            return True
        except:
            return False


class SpecUser(User):
    USER_TYPE = (
        ('developer','Developer'),
        ('lender','Lender'),
        ('banker','Banker'),
        ('dealer','Dealer'),
        ('homeowner','Prospective Homeowner'),
        ('Municipality/Government Official','Municipality/Government Official'),
        ('vendor','Vendor'),
    )

    user_type = models.CharField('Sign up as', max_length=32, choices = USER_TYPE, default = None)
    company_name = models.CharField('Name of Company',max_length=100, blank=True, null=True)
    title = models.CharField('Title',max_length=100, blank=True, null=True)
    phone_number = models.CharField(("Phone Number"), max_length = 18, help_text="optional", blank=True, null=True)
    dealer_no = models.CharField('Dealer Number',max_length=6, help_text="optional", validators=[RegexValidator(r"^[0-9]*$")] ,blank=True, null=True)
    home_permission = models.BooleanField('Home Access', default=False)
    content_permission = models.BooleanField('Content Access', default=False)
    activation_time_home = models.DateTimeField('Activation Time (Home)',blank=True, null=True)
    expire_time_home = models.DateTimeField('Expire Time (Home)', blank=True, null=True) 
    activation_time_spec_content = models.DateTimeField('Activation Time (Content)',blank=True, null=True)
    expire_time_spec_content = models.DateTimeField('Expire Time (Content)', blank=True, null=True) 

    city = models.CharField('City',max_length=60, default='', blank=True, null=True)
    postal = models.CharField('Postal',max_length=60, default='', blank=True, null=True)
    state = models.CharField('State',max_length=60, default='', blank=True, null=True)
    country = models.CharField('Country',max_length=60, default='', blank=True, null=True)
    address = models.CharField('Address', max_length=1000, default='', blank=True, null=True)

    def __str__(self):
        return f"{self.user_type} - {self.first_name}"

    class Meta:
        verbose_name = 'Spec_User'
        verbose_name_plural = 'Spec User'


class EmailList(models.Model):
    # name = models.CharField("Name", max_length=60, blank=True, null=True, default=None)
    email = models.EmailField(("Email"), max_length=254, unique=True)


class UserPreferences(models.Model):
    YES_NO_CHOICES = (
        ('yes', 'Yes'),
        ('no', 'No')
    )
    Type_Of_Development = (
        ('select all','Select All'),
        ('Commercial','Commercial'),
        ('Mixed-use','Mixed-use'),
        ('Multi-tenant','Multi-tenant'),
        ('Condominium','Condominium'),
        ('Townhome','Townhome'),
        ('Man Camp','Man Camp'),
        ('Mobile Home Park','Mobile Home Park'),
        ('RV Park','RV Park'),
        ('Park Home (as defined by Housing and Urban Development)','Park Home (as defined by Housing and Urban Development)'),
        ('Other','Other'),
    )
   
    Type_Of_Smart_Home = (
    ('Automated Home Shopping and Delivery','Automated Home Shopping and Delivery'),
    ('Self-Driving Transport to Local Shopping Centers','Self-Driving Transport to Local Shopping Centers'),
    ('Self-Driving Transport to Local Medical Facilities','Self-Driving Transport to Local Medical Facilities'),
    )
    Type_Of_Electric_Vehicle_Function = (
        ('Standard','Standard'),
        ('Capability to Load Handicapped Person Without Human Assistance','Capability to Load Handicapped Person Without Human Assistance'),
    )

    user_obj = models.ForeignKey(SpecUser, on_delete=models.CASCADE, null=True,blank=True)
    type_of_development = MultiSelectField("What type of development(s) are you seeking?",choices=Type_Of_Development, max_length=300)

    other_type_of_development = models.CharField(max_length=300, verbose_name="Other", blank=True, null=True)
   
    type_of_smart_home = MultiSelectField("What type of smart home functionality are you interested in learning more about? ",choices=Type_Of_Smart_Home, max_length=300)
   
    type_of_electric_vehicle_function = MultiSelectField("An electric vehicle will be included with each housing unit. What type of electric vehicle function are you interested in?",choices=Type_Of_Electric_Vehicle_Function, max_length=300)

    learn_about_electric_drive = models.CharField("Do you wish to learn more about an optional electric-drive community transport vehicle?",choices=YES_NO_CHOICES, max_length=100)

    class Meta:
        verbose_name = 'UserPreference'
        verbose_name_plural = 'UserPreferences'


class ModelsInfo(models.Model):
    model_name = models.CharField('Model name',max_length=60, default='', blank=True, null=True)
    model_dimension = models.CharField('Model Dimensions',max_length=60, default='', blank=True, null=True)
    model_header = models.CharField('Model Header',max_length=60, default='', blank=True, null=True)
    model_text = models.TextField('Text', default='', blank=True, null=True)
    beds = models.CharField('Beds',max_length=60, default='', blank=True, null=True)
    baths = models.CharField('Baths',max_length=60, default='', blank=True, null=True)
    sq_ft = models.CharField('SQ.ft',max_length=60, default='', blank=True, null=True)
    parking_spaces = models.CharField('Parking Spaces',max_length=60, default='', blank=True, null=True)
    no_of_kitchen = models.CharField('Number of Kitchen',max_length=60, default='', blank=True, null=True)
    kitchen = models.CharField('Kitchen',max_length=60, default='', blank=True, null=True)
    bathroom = models.CharField('Bathroom',max_length=60, default='', blank=True, null=True)
    frame_material = models.CharField('Frame Material',max_length=60, default='', blank=True, null=True)
    price = models.CharField('Price',max_length=60, default='', blank=True, null=True)
    amenities = models.CharField('Amenities',max_length=60, default='', blank=True, null=True)
    floor = models.CharField('floor',max_length=60, default='', blank=True, null=True)
    garage = models.CharField('Garage',max_length=60, default='', blank=True, null=True)
    fireplace = models.CharField('Fireplace',max_length=60, default='', blank=True, null=True)
    laundry = models.CharField('Laundry',max_length=60, default='', blank=True, null=True)
    interior_features = models.CharField('Interior Features',max_length=60, default='', blank=True, null=True)
    construction_material = models.CharField('Construction Materials',max_length=60, default='', blank=True, null=True)


class ModelImages(models.Model):
    modelsinfo_obj = models.ForeignKey(ModelsInfo, on_delete=models.CASCADE)
    path = models.CharField('Beds',max_length=900, default='', blank=True, null=True)
    pdf_file_path = models.CharField('Beds',max_length=900, default='', blank=True, null=True)

order/templates/order/3story2w_3dmodel.html
{% extends 'users/base.html' %}
{% load static %}

{% block content %}
	<div class="container-fluid">
		<h2 class="text-center mb-4"><strong>Virtual Visit</strong></h2>
		<div class="row">
			<div id="_3d_render" class="col-md-12 col-sm-12">
				<iframe height=100% width=100% src="https://boltonbloks.shapespark.com/3-storey_house/">
				</iframe>
			</div>
		</div>
	</div>
{% endblock %}

order/templates/order/dealer_homeowner.html
{% extends "users/base.html" %}

{% load static %}
{% block content%}

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="table-responsive">
                
            <table class="view_order_table table table-striped table-bordered animate zoomIn">
                <legend class="text-center" ><b>Prospective Homeowners</b></legend>
                <tr>
                <th>#</th><th>First Name</th><th>Last Name</th><th>Email</th><th>Phone Number</th></tr>
                {% for order in orders %}
                    <tr>
                        <th><strong>{{forloop.counter}}</strong></th>
                        <td>{{order.first_name}}</td>
                        <td>{{order.last_name}}</td>
                        <td>{{order.email}}</td>
                        <td>{{order.phone_number}}</td>            
                    </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>
</div>

{% endblock%}

{% block js %}
{% if request.user.is_authenticated != True %}

<script>
    var time = {{time|safe}};
    var uid = "{{uid|safe}}";   
    let input = [time,uid]
 
    function counter(time_left,uid) {
     var expiryTime = time_left;
     var time = $('.counter').val();
     time = parseInt
     time = time + 1;
     if(time > expiryTime) {
          window.location.href = "/buyer/applications/"+uid;	 
     }
     else {
 $('.counter').val;
     }
}

console.log('trying')

setInterval(counter,1000,...input);

</script>
{% endif %}
{% endblock %}

order/templates/order/delivery_info.html
{% extends 'users/base.html' %}
{% load static %}
{% block content %}

<div id="tabs" class="container project-tab custom_font2">
	<div class="row">
		<div class="col-md-8 m-auto p-0 pb-5 bottom_border">
			<form method="POST" class="custom_input">
			<p class="text-center text-uppercase text-muted">Checkout - Step {{wizard.steps.step1}} of
					 {{wizard.steps.count}}</p>
				<h3 class="mt-5 mb-5">Shipping Information</h3>
				{% csrf_token %}
				{{ wizard.management_form }}
				{% for field in wizard.form %}
					{% if field == wizard.form.state %}
						 <div class="w-100" style="width: 100%; display:flex;">
								<label for="id_state">{{ wizard.form.state.label }}</label>
								<div style=" margin-top: 60px; margin-left: -65px;">
									 {{ wizard.form.state }}
								</div>
								<label for="id_postal" style="position: relative; left: 18px;"
								>{{ wizard.form.postal.label }}</label>
								<div style="margin-top: 60px; margin-left:-53px;">
									 {{ wizard.form.postal }}
								</div>
						 </div>
					{% elif field == wizard.form.postal %}
					{% else %}
						<label>{{ field.label }}</label>
						{{ field }}
					{% endif %}
				{% endfor %}
				 <br/><br/>
				 {% include "users/formwizard_btns.html" %}<br/><br/>
			</form>
		</div>
	</div>
</div>

{% endblock %}

order/templates/order/login.html
{% extends "users/base.html"%}
{% load crispy_forms_tags %}

{% block content %}
<div class="sm-padding"></div>
<div class="container quicksand-font">
    <div class="row mt-5 mb-4">
<div class="col-md-6 pt-4 pb-5">
			<h1 class="text-center create_acct_h1 mb-4"><b>Sign In</b></h1>
			<div class="w-100 bg-white mt-5 pb-3" style="border-radius: 20px;">
				<form method="POST" action="/login/">
					{% csrf_token %}
					<div class="form-group">
						<div style="margin-left: -20px;" class="custom_input">
							<i class="prefix"> </i>
							<label for="login-email" class="label" data-error="wrong"
								   data-success="right">Email</label><br>
							<input type="email" id="login-email" name="username" required>
						</div>
						<div style="margin-left: -20px;"class="custom_input">
							<i class="prefix"> </i>
							<label for="login-password" class="label" data-error="wrong"
								   data-success="right">Password*</label><br>
							<input type="password" id="login-password" name="password" required>
						</div>
						<div class="w-100 mt-2">
							<small>
							<a class="fa-pull-right forget-pass" href="{% url 'password_reset' %}"> Forgot Password? </a>
							</small>
						</div>
						<br>
						<div class="w-100 mt-4 text-center">
							<button class="btn btn-custom btn-lg pl-5 pr-5" type="submit">Login</button>
						</div>
					</div>
				</form>
			</div>
		</div>
    </div>
</div>

{% endblock content %}

order/templates/order/order_mail_to_admin.html
{% load static %}
{% load humanize %}
{% autoescape on %}

<table align="center" width="100%" border="0" cellspacing="0" cellpadding="0" style="min-width:800px;margin-top: 60px; font-size: 14px;">
	<tbody>
		<tr>
			<td align="center" width="100%">
				<table align="center" width="800" border="0" bgcolor="#F2F2F2" cellpadding="0" cellspacing="0">
					<tbody>
						<tr
							style='font-family: -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,"Noto Sans",sans-serif,"Apple Color Emoji","Segoe UI Emoji","Segoe UI Symbol","Noto Color Emoji";'>
							<td style="padding-left: 60px;padding-right: 60px;text-align: justify;">
								<br />
								<table>
									<tbody>
										<tr>
											<td><img src="http://{{ domain }}{% static 'users/imgs/arc_logo.png' %}"
													width="120" height="90" border="0"></td>
											<td style="padding-left: 60px;"><h1 class=" col text-center c-header"
												style="text-align: center !important;font-weight: 700;">Order Inquiry</h1>
											</td>
										</tr>
									</tbody>
                                </table>
                                

								<br/>
								<span>
									Hi <b>Admin</a></b>,
								</span>
								<br /><br/>
								<span>
									It is a pleasure to inform you that {{ form.f_name }} {{form.l_name}} has placed an order.
								</span>
							</td>
                        </tr><br>

        <table style='text-align:left; padding: 0 10px 0 60px'>
                <tr>
                </tr>
                
                <tr><th>Company Name:</th>
                    <td colspan="2"></td>
                    <td>{{form.company_name}}</td>
                </tr><br>
                <tr><th>First Name:</th>
                    <td colspan="2"></td>
                    <td>{{form.f_name}}</td>
                </tr><br>
                <tr><th>Last Name:</th>
                    <td colspan="2"></td>
                    <td>{{form.l_name}}</td>
                </tr><br>
                <tr><th>Email:</th>
                    <td colspan="2"></td>
                    <td>{{form.email}}</td>
                </tr><br>
                <tr><th>Phone Number:</th>
                    <td colspan="2"></td>
                    <td>{{form.phone_number}}</td>
                </tr><br>
                <tr><th>Zip Code:</th>
                    <td colspan="2"></td>
                    <td>{{form.zipcode}}</td>
                </tr><br>
                {% if form.how_much_letter_of_credit %}
                <tr><th>Value of your Letter of Credit (in USD)</th>
                    <td colspan="2"></td>
                    <td>$ {{form.how_much_letter_of_credit|intcomma}}</td>
                </tr><br>
                {% endif %}
                {% if form.how_much_line_of_credit %}
                <tr><th>What is the currently unused amount in your Line of Credit?</th>
                    <td colspan="2"></td>
                    <td>$ {{form.how_much_line_of_credit|intcomma}}</td>
                </tr><br>
                {% endif %}

                <tr><th>When to Order</th>
                    <td colspan="2"></td>
                    {% if form.when_to_order != 'other' %}
                    <td>{{form.when_to_order}}</td>
                    {% elif form.when_to_order == 'other' %}
                    <td>Within {{form.other_when_to_order}} Days</td>
                    {% endif %}
                </tr><br>
                <tr><th>What type of development(s) are you seeking?</th>
                    <td colspan="2"></td>
                    <td>
                    {% for i in form.type_of_development %} 
                    {% if i == 'select all' or i == 'Other' %}
                    {% else%}
                        {{i}} ,
                    {% endif %}
                    {% endfor%}
                    {% if form.other_type_of_development %}
                    ({{form.other_type_of_development}}).</td>
                    {% endif %}
                    
                </tr><br>

                <tr><th>On which type of climate area(s) will the development(s) be sited?</th>
                    <td colspan="2"></td>
                    <td>
                    {% for i in form.type_of_climate_area %} 
                    {% if i == 'select all' or i == 'Other' %}
                    {% else%}
                        {{i}},
                    {% endif %}
                    {% endfor%}
                    {% if form.other_type_of_climate_area %}
                    ({{form.other_type_of_climate_area}}).</td>
                    {% endif %}
                    
                </tr>   <br> 

                <tr><th>What type of smart home functionality are you interested in learning more about?</th>
                    <td colspan="2"></td>
                    <td>
                    {% for i in form.type_of_smart_home %} 
                        {{i}},
                    {% endfor%}</td>
                </tr> <br>

                <tr><th>Type of  Electric Vehicle Function</th>
                    <td colspan="2"></td>
                    <td>
                    {% for i in form.type_of_electric_vehicle_function %} 
                        {{i}},
                    {% endfor%}</td>
                </tr> <br>
                {% if form.learn_about_electric_drive %}
                <tr><th>Learn About Electric Drive</th>
                    <td colspan="2"></td>
                    <td>{{form.learn_about_electric_drive}}</td>
                </tr> <br>
                {% endif %}

                {% if form.septic_infrastructure %}
                <tr><th>Does the development site already have septic infrastructure or service?</th>
                    <td colspan="2"></td>
                    <td>{{form.septic_infrastructure}}</td>
                </tr> <br>
                {% endif %}

                {% if form.installation_septic_infrastructure  %}
                <tr><th>Does it require the Installation of Septic Infrastructure? </th>
                    <td colspan="2"></td>
                    <td>{{form.installation_septic_infrastructure}} </td>
                </tr> <br>
                {% endif %}

            </table>

						<tr
							style='font-family: -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,"Noto Sans",sans-serif,"Apple Color Emoji","Segoe UI Emoji","Segoe UI Symbol","Noto Color Emoji";'>
							<td style="padding-left: 60px;padding-right: 60px;text-align: justify;">
								<br />
								<br /><br />
								<span>
									Thanks,<br /> <b>Team BoltonBloks</b>
								</span>
								<br /> <br /> <br />
							</td>
						</tr>
					</tbody>
				</table>
			</td>
		</tr>
	</tbody>
</table>


{% endautoescape %}

order/templates/order/video.html
{% extends "users/base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block content%}

<div class="container">
    <div class="row">
        <div class="col-md-12 col-sm-12">
        <iframe width="920" height="640" src="https://www.youtube.com/embed/VEOI3soYuAk" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        </div>
    </div>
</div>

{% endblock%}